packages:
    - 'packages/*'
    - 'apps/*'
    - 'tooling/*'
    - 'internal/*'
    - 'libraries/*'
    - 'libraries/design-system/*'
    - 'cloudflare/*'
    - 'dub-packages/*'
    - 'dub-packages/embeds/*'