packages:
    - 'packages/*'
    - 'apps/*'
    - 'tooling/*'
    - 'internal/*'
    - 'libraries/*'
    - 'libraries/design-system/*'
    - 'libraries/embeds/*'
    - 'cloudflare/*'
    - 'database/*'
    - 'apps/web/.react-email'
    - 'docs/*'
