FROM node:18.19.0 AS base

RUN npm install -g pnpm@8.15.4 turbo@1.12.4 && \
    corepack enable

FROM base AS builder
WORKDIR /solomonai
COPY . .
RUN turbo prune api --docker

FROM base AS installer
WORKDIR /solomonai

# First install dependencies (as they change less often)
COPY .gitignore .gitignore
COPY --from=builder /solomonai/out/json/ .
COPY --from=builder /solomonai/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN pnpm install --frozen-lockfile

# Build the project and its dependencies
COPY --from=builder /solomonai/out/full/ .
COPY turbo.json turbo.json
RUN pnpm turbo build --filter=api...

FROM base AS runner
WORKDIR /solomonai
COPY --from=installer /solomonai .

WORKDIR /solomonai/services/financial-service
ENV WRANGLER_SEND_METRICS=false
RUN rm .dev.vars || true

CMD ["pnpm", "wrangler", "dev"] 