// This file was generated by basehub. Do not edit directly. Read more: https://basehub.com/docs/api-reference/basehub-sdk

/* eslint-disable */
/* eslint-disable eslint-comments/no-restricted-disable */
/* tslint:disable */

// .basehub/runtime/_error.ts
var GenqlError = class extends Error {
  constructor(errors, data) {
    let message = Array.isArray(errors) ? errors.map((x) => x?.message || "").join("\n") : "";
    if (!message) {
      message = "GraphQL error";
    }
    super(message);
    this.errors = [];
    this.errors = errors;
    this.data = data;
  }
};

// .basehub/runtime/_batcher.ts
function dispatchQueueBatch(client, queue) {
  let batchedQuery = queue.map((item) => item.request);
  if (batchedQuery.length === 1) {
    batchedQuery = batchedQuery[0];
  }
  ;
  (() => {
    try {
      return client.fetcher(batchedQuery);
    } catch (e) {
      return Promise.reject(e);
    }
  })().then((responses) => {
    if (queue.length === 1 && !Array.isArray(responses)) {
      if (responses.errors && responses.errors.length) {
        queue[0].reject(
          new GenqlError(responses.errors, responses.data)
        );
        return;
      }
      queue[0].resolve(responses);
      return;
    } else if (responses.length !== queue.length) {
      throw new Error("response length did not match query length");
    }
    for (let i = 0; i < queue.length; i++) {
      if (responses[i].errors && responses[i].errors.length) {
        queue[i].reject(
          new GenqlError(responses[i].errors, responses[i].data)
        );
      } else {
        queue[i].resolve(responses[i]);
      }
    }
  }).catch((e) => {
    for (let i = 0; i < queue.length; i++) {
      queue[i].reject(e);
    }
  });
}
function dispatchQueue(client, options) {
  const queue = client._queue;
  const maxBatchSize = options.maxBatchSize || 0;
  client._queue = [];
  if (maxBatchSize > 0 && maxBatchSize < queue.length) {
    for (let i = 0; i < queue.length / maxBatchSize; i++) {
      dispatchQueueBatch(
        client,
        queue.slice(i * maxBatchSize, (i + 1) * maxBatchSize)
      );
    }
  } else {
    dispatchQueueBatch(client, queue);
  }
}
var QueryBatcher = class _QueryBatcher {
  constructor(fetcher, {
    batchInterval = 16,
    shouldBatch = true,
    maxBatchSize = 0
  } = {}) {
    this.fetcher = fetcher;
    this._options = {
      batchInterval,
      shouldBatch,
      maxBatchSize
    };
    this._queue = [];
  }
  /**
   * Fetch will send a graphql request and return the parsed json.
   * @param {string}      query          - the graphql query.
   * @param {Variables}   variables      - any variables you wish to inject as key/value pairs.
   * @param {[string]}    operationName  - the graphql operationName.
   * @param {Options}     overrides      - the client options overrides.
   *
   * @return {promise} resolves to parsed json of server response
   *
   * @example
   * client.fetch(`
   *    query getHuman($id: ID!) {
   *      human(id: $id) {
   *        name
   *        height
   *      }
   *    }
   * `, { id: "1001" }, 'getHuman')
   *    .then(human => {
   *      // do something with human
   *      console.log(human);
   *    });
   */
  fetch(query, variables, operationName, overrides = {}) {
    const request = {
      query
    };
    const options = Object.assign({}, this._options, overrides);
    if (variables) {
      request.variables = variables;
    }
    if (operationName) {
      request.operationName = operationName;
    }
    const promise = new Promise((resolve, reject) => {
      this._queue.push({
        request,
        resolve,
        reject
      });
      if (this._queue.length === 1) {
        if (options.shouldBatch) {
          setTimeout(
            () => dispatchQueue(this, options),
            options.batchInterval
          );
        } else {
          dispatchQueue(this, options);
        }
      }
    });
    return promise;
  }
  /**
   * Fetch will send a graphql request and return the parsed json.
   * @param {string}      query          - the graphql query.
   * @param {Variables}   variables      - any variables you wish to inject as key/value pairs.
   * @param {[string]}    operationName  - the graphql operationName.
   * @param {Options}     overrides      - the client options overrides.
   *
   * @return {Promise<Array<Result>>} resolves to parsed json of server response
   *
   * @example
   * client.forceFetch(`
   *    query getHuman($id: ID!) {
   *      human(id: $id) {
   *        name
   *        height
   *      }
   *    }
   * `, { id: "1001" }, 'getHuman')
   *    .then(human => {
   *      // do something with human
   *      console.log(human);
   *    });
   */
  forceFetch(query, variables, operationName, overrides = {}) {
    const request = {
      query
    };
    const options = Object.assign({}, this._options, overrides, {
      shouldBatch: false
    });
    if (variables) {
      request.variables = variables;
    }
    if (operationName) {
      request.operationName = operationName;
    }
    const promise = new Promise((resolve, reject) => {
      const client = new _QueryBatcher(this.fetcher, this._options);
      client._queue = [
        {
          request,
          resolve,
          reject
        }
      ];
      dispatchQueue(client, options);
    });
    return promise;
  }
};

// .basehub/runtime/_fetcher.ts
var DEFAULT_BATCH_OPTIONS = {
  maxBatchSize: 10,
  batchInterval: 40
};
var createFetcher = ({
  url,
  headers = {},
  fetcher,
  fetch: _fetch,
  batch = false,
  ...rest
}) => {
  if (!url && !fetcher) {
    throw new Error("url or fetcher is required");
  }
  fetcher = fetcher || (async (body, extraFetchOptions) => {
    let headersObject = typeof headers == "function" ? await headers() : headers;
    headersObject = headersObject || {};
    if (typeof fetch === "undefined" && !_fetch) {
      throw new Error(
        "Global `fetch` function is not available, pass a fetch polyfill to Genql `createClient`"
      );
    }
    let fetchImpl = _fetch || fetch;
    if (extraFetchOptions?.headers) {
      headersObject = {
        ...headersObject,
        ...extraFetchOptions.headers
      };
      delete extraFetchOptions.headers;
    }
    const res = await fetchImpl(url, {
      headers: {
        "Content-Type": "application/json",
        ...headersObject
      },
      method: "POST",
      body: JSON.stringify(body),
      ...rest,
      ...extraFetchOptions
    });
    if (!res.ok) {
      throw new Error(`${res.statusText}: ${await res.text()}`);
    }
    const json = await res.json();
    return json;
  });
  if (!batch) {
    return async (body, extraFetchOptions) => {
      const json = await fetcher(body, extraFetchOptions);
      if (Array.isArray(json)) {
        return json.map((json2) => {
          if (json2?.errors?.length) {
            throw new GenqlError(json2.errors || [], json2.data);
          }
          return json2.data;
        });
      } else {
        if (json?.errors?.length) {
          throw new GenqlError(json.errors || [], json.data);
        }
        return json.data;
      }
    };
  }
  const batcher = new QueryBatcher(
    async (batchedQuery, extraFetchOptions) => {
      const json = await fetcher(batchedQuery, extraFetchOptions);
      return json;
    },
    batch === true ? DEFAULT_BATCH_OPTIONS : batch
  );
  return async ({ query, variables }) => {
    const json = await batcher.fetch(query, variables);
    if (json?.data) {
      return json.data;
    }
    throw new Error(
      "Genql batch fetcher returned unexpected result " + JSON.stringify(json)
    );
  };
};

// .basehub/runtime/_aliasing.js
var aliasSeparator = "__alias__";
function replaceSystemAliases(obj) {
  if (typeof obj !== "object" || obj === null) {
    return obj;
  }
  if (Array.isArray(obj)) {
    return obj.map((item) => replaceSystemAliases(item));
  }
  const newObj = {};
  for (const [key, value] of Object.entries(obj)) {
    if (key.includes(aliasSeparator)) {
      const [_prefix, ...rest] = key.split(aliasSeparator);
      const newKey = rest.join(aliasSeparator);
      newObj[newKey] = replaceSystemAliases(value);
    } else {
      newObj[key] = replaceSystemAliases(value);
    }
  }
  return newObj;
}

// .basehub/runtime/_generate-graphql-operation.ts
var parseRequest = (request, ctx, path, options) => {
  if (typeof request === "object" && "__args" in request) {
    const args = request.__args;
    let fields = { ...request };
    delete fields.__args;
    const argNames = Object.keys(args);
    if (argNames.length === 0) {
      return parseRequest(fields, ctx, path, options);
    }
    const field = getFieldFromPath(ctx.root, path);
    const argStrings = argNames.map((argName) => {
      ctx.varCounter++;
      const varName = `v${ctx.varCounter}`;
      const typing = field.args && field.args[argName];
      if (!typing) {
        throw new Error(
          `no typing defined for argument \`${argName}\` in path \`${path.join(
            "."
          )}\``
        );
      }
      const shouldStringifyValue = ["String", "String!"].includes(
        typing[1]
      );
      let value = args[argName];
      if (shouldStringifyValue) {
        if (typeof value === "object") {
          value = JSON.stringify(value);
        }
      }
      ctx.variables[varName] = {
        value,
        typing
      };
      return `${argName}:$${varName}`;
    });
    return `(${argStrings})${parseRequest(fields, ctx, path, options)}`;
  } else if (typeof request === "object" && Object.keys(request).length > 0) {
    const fields = request;
    const fieldNames = Object.keys(fields).filter((k) => Boolean(fields[k]));
    if (fieldNames.length === 0) {
      throw new Error(
        `field selection should not be empty: ${path.join(".")}`
      );
    }
    const type = path.length > 0 ? getFieldFromPath(ctx.root, path).type : ctx.root;
    const scalarFields = type.scalar;
    let scalarFieldsFragment;
    if (fieldNames.includes("__scalar")) {
      const falsyFieldNames = new Set(
        Object.keys(fields).filter((k) => !Boolean(fields[k]))
      );
      if (scalarFields?.length) {
        ctx.fragmentCounter++;
        scalarFieldsFragment = `f${ctx.fragmentCounter}`;
        ctx.fragments.push(
          `fragment ${scalarFieldsFragment} on ${type.name}{${scalarFields.filter((f) => !falsyFieldNames.has(f)).map(
            (f) => `${options?.aliasPrefix ? `${options.aliasPrefix}${aliasSeparator}${f}: ` : ""}${f}`
          ).join(",")}}`
        );
      }
    }
    const fieldsSelection = fieldNames.filter((f) => !["__scalar", "__name", "__fragmentOn"].includes(f)).map((f) => {
      if (f.startsWith("on_")) {
        ctx.fragmentCounter++;
        const implementationFragment = `f${ctx.fragmentCounter}`;
        const parsed = parseRequest(fields[f], ctx, [...path, f], {
          ...options,
          aliasPrefix: implementationFragment
        });
        const typeMatch = f.match(/^on_(.+)/);
        if (!typeMatch || !typeMatch[1])
          throw new Error("match failed");
        ctx.fragments.push(
          `fragment ${implementationFragment} on ${typeMatch[1]}${parsed}`
        );
        return `...${implementationFragment}`;
      } else {
        const parsed = parseRequest(
          fields[f],
          ctx,
          [...path, f],
          options
        );
        return `${options?.aliasPrefix ? `${options.aliasPrefix}${aliasSeparator}${f}: ` : ""}${f}${parsed}`;
      }
    }).concat(scalarFieldsFragment ? [`...${scalarFieldsFragment}`] : []).join(",");
    return `{${fieldsSelection}}`;
  } else {
    return "";
  }
};
var generateGraphqlOperation = (operation, root, fields) => {
  const ctx = {
    root,
    varCounter: 0,
    variables: {},
    fragmentCounter: 0,
    fragments: []
  };
  const result = parseRequest(fields, ctx, []);
  const varNames = Object.keys(ctx.variables);
  const varsString = varNames.length > 0 ? `(${varNames.map((v) => {
    const variableType = ctx.variables[v].typing[1];
    return `$${v}:${variableType}`;
  })})` : "";
  const operationName = fields?.__name || "";
  return {
    query: [
      `${operation} ${operationName}${varsString}${result}`,
      ...ctx.fragments
    ].join(","),
    variables: Object.keys(ctx.variables).reduce(
      (r, v) => {
        r[v] = ctx.variables[v].value;
        return r;
      },
      {}
    ),
    ...operationName ? { operationName: operationName.toString() } : {}
  };
};
var getFieldFromPath = (root, path) => {
  let current;
  if (!root)
    throw new Error("root type is not provided");
  if (path.length === 0)
    throw new Error(`path is empty`);
  path.forEach((f) => {
    const type = current ? current.type : root;
    if (!type.fields)
      throw new Error(`type \`${type.name}\` does not have fields`);
    const possibleTypes = Object.keys(type.fields).filter((i) => i.startsWith("on_")).reduce(
      (types, fieldName) => {
        const field2 = type.fields && type.fields[fieldName];
        if (field2)
          types.push(field2.type);
        return types;
      },
      [type]
    );
    let field = null;
    possibleTypes.forEach((type2) => {
      const found = type2.fields && type2.fields[f];
      if (found)
        field = found;
    });
    if (!field)
      throw new Error(
        `type \`${type.name}\` does not have a field \`${f}\``
      );
    current = field;
  });
  return current;
};

// .basehub/runtime/_create-client.ts
var createClient = ({
  queryRoot,
  mutationRoot,
  subscriptionRoot,
  getExtraFetchOptions,
  ...options
}) => {
  const fetcher = createFetcher(options);
  const client = {};
  if (queryRoot) {
    client.query = async (request) => {
      if (!queryRoot)
        throw new Error("queryRoot argument is missing");
      const body = generateGraphqlOperation("query", queryRoot, request);
      const extraFetchOptions = await getExtraFetchOptions?.(
        "query",
        body,
        request
      );
      return await fetcher(body, extraFetchOptions).then(
        (result) => replaceSystemAliases(result)
      );
    };
  }
  if (mutationRoot) {
    client.mutation = async (request) => {
      if (!mutationRoot)
        throw new Error("mutationRoot argument is missing");
      const body = generateGraphqlOperation(
        "mutation",
        mutationRoot,
        request
      );
      const extraFetchOptions = await getExtraFetchOptions?.(
        "mutation",
        body,
        request
      );
      return await fetcher(
        generateGraphqlOperation("mutation", mutationRoot, request),
        extraFetchOptions
      );
    };
  }
  return client;
};
createClient.replaceSystemAliases = replaceSystemAliases;

// .basehub/runtime/_link-type-map.ts
var linkTypeMap = (typeMap2) => {
  const indexToName = Object.assign(
    {},
    ...Object.keys(typeMap2.types).map((k, i) => ({ [i]: k }))
  );
  let intermediaryTypeMap = Object.assign(
    {},
    ...Object.keys(typeMap2.types || {}).map(
      (k) => {
        const type = typeMap2.types[k];
        const fields = type || {};
        return {
          [k]: {
            name: k,
            // type scalar properties
            scalar: Object.keys(fields).filter((f) => {
              const [type2] = fields[f] || [];
              const isScalar = type2 && typeMap2.scalars.includes(type2);
              if (!isScalar) {
                return false;
              }
              const args = fields[f]?.[1];
              const argTypes = Object.values(args || {}).map((x) => x?.[1]).filter(Boolean);
              const hasRequiredArgs = argTypes.some(
                (str) => str && str.endsWith("!")
              );
              if (hasRequiredArgs) {
                return false;
              }
              return true;
            }),
            // fields with corresponding `type` and `args`
            fields: Object.assign(
              {},
              ...Object.keys(fields).map(
                (f) => {
                  const [typeIndex, args] = fields[f] || [];
                  if (typeIndex == null) {
                    return {};
                  }
                  return {
                    [f]: {
                      // replace index with type name
                      type: indexToName[typeIndex],
                      args: Object.assign(
                        {},
                        ...Object.keys(args || {}).map(
                          (k2) => {
                            if (!args || !args[k2]) {
                              return;
                            }
                            const [
                              argTypeName,
                              argTypeString
                            ] = args[k2];
                            return {
                              [k2]: [
                                indexToName[argTypeName],
                                argTypeString || indexToName[argTypeName]
                              ]
                            };
                          }
                        )
                      )
                    }
                  };
                }
              )
            )
          }
        };
      }
    )
  );
  const res = resolveConcreteTypes(intermediaryTypeMap);
  return res;
};
var resolveConcreteTypes = (linkedTypeMap) => {
  Object.keys(linkedTypeMap).forEach((typeNameFromKey) => {
    const type = linkedTypeMap[typeNameFromKey];
    if (!type.fields) {
      return;
    }
    const fields = type.fields;
    Object.keys(fields).forEach((f) => {
      const field = fields[f];
      if (field.args) {
        const args = field.args;
        Object.keys(args).forEach((key) => {
          const arg = args[key];
          if (arg) {
            const [typeName2] = arg;
            if (typeof typeName2 === "string") {
              if (!linkedTypeMap[typeName2]) {
                linkedTypeMap[typeName2] = { name: typeName2 };
              }
              arg[0] = linkedTypeMap[typeName2];
            }
          }
        });
      }
      const typeName = field.type;
      if (typeof typeName === "string") {
        if (!linkedTypeMap[typeName]) {
          linkedTypeMap[typeName] = { name: typeName };
        }
        field.type = linkedTypeMap[typeName];
      }
    });
  });
  return linkedTypeMap;
};

// .basehub/types.ts
var types_default = {
  "scalars": [
    0,
    6,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    36,
    41,
    43,
    48,
    49,
    51,
    54,
    55,
    63,
    73,
    74,
    81
  ],
  "types": {
    "AnalyticsKeyScope": {},
    "Articles": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_meta": [
        57
      ],
      "_searchKey": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "item": [
        2
      ],
      "items": [
        2
      ],
      "__typename": [
        74
      ]
    },
    "ArticlesItem": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "author": [
        8
      ],
      "body": [
        34
      ],
      "excerpt": [
        74
      ],
      "ogImage": [
        31
      ],
      "related": [
        2
      ],
      "__typename": [
        74
      ]
    },
    "ArticlesItemFilterInput": {
      "AND": [
        3
      ],
      "OR": [
        3
      ],
      "_sys_apiNamePath": [
        75
      ],
      "_sys_createdAt": [
        47
      ],
      "_sys_hash": [
        75
      ],
      "_sys_id": [
        75
      ],
      "_sys_idPath": [
        75
      ],
      "_sys_lastModifiedAt": [
        47
      ],
      "_sys_slug": [
        75
      ],
      "_sys_slugPath": [
        75
      ],
      "_sys_title": [
        75
      ],
      "author": [
        4
      ],
      "excerpt": [
        75
      ],
      "related": [
        5
      ],
      "__typename": [
        74
      ]
    },
    "ArticlesItemFilterInput__author_0___untitled": {
      "_sys_apiNamePath": [
        75
      ],
      "_sys_createdAt": [
        47
      ],
      "_sys_hash": [
        75
      ],
      "_sys_id": [
        75
      ],
      "_sys_idPath": [
        75
      ],
      "_sys_lastModifiedAt": [
        47
      ],
      "_sys_slug": [
        75
      ],
      "_sys_slugPath": [
        75
      ],
      "_sys_title": [
        75
      ],
      "xProfile": [
        75
      ],
      "__typename": [
        74
      ]
    },
    "ArticlesItemFilterInput__related_0___untitled": {
      "_sys_apiNamePath": [
        75
      ],
      "_sys_createdAt": [
        47
      ],
      "_sys_hash": [
        75
      ],
      "_sys_id": [
        75
      ],
      "_sys_idPath": [
        75
      ],
      "_sys_lastModifiedAt": [
        47
      ],
      "_sys_slug": [
        75
      ],
      "_sys_slugPath": [
        75
      ],
      "_sys_title": [
        75
      ],
      "excerpt": [
        75
      ],
      "__typename": [
        74
      ]
    },
    "ArticlesItemOrderByEnum": {},
    "Authors": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_meta": [
        57
      ],
      "_searchKey": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "item": [
        8
      ],
      "items": [
        8
      ],
      "__typename": [
        74
      ]
    },
    "AuthorsItem": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "avatar": [
        29
      ],
      "xProfile": [
        74
      ],
      "__typename": [
        74
      ]
    },
    "AuthorsItemFilterInput": {
      "AND": [
        9
      ],
      "OR": [
        9
      ],
      "_sys_apiNamePath": [
        75
      ],
      "_sys_createdAt": [
        47
      ],
      "_sys_hash": [
        75
      ],
      "_sys_id": [
        75
      ],
      "_sys_idPath": [
        75
      ],
      "_sys_lastModifiedAt": [
        47
      ],
      "_sys_slug": [
        75
      ],
      "_sys_slugPath": [
        75
      ],
      "_sys_title": [
        75
      ],
      "xProfile": [
        75
      ],
      "__typename": [
        74
      ]
    },
    "AuthorsItemOrderByEnum": {},
    "BSHBEventSchema": {},
    "BSHBRichTextContentSchema": {},
    "BSHBRichTextTOCSchema": {},
    "BSHBSelect_83162882": {},
    "BSHBSelect_337363946": {},
    "BSHBSelect_893959412": {},
    "BSHBSelect_2084155347": {},
    "BSHBSelect_2125218645": {},
    "BSHBSelect__669079093": {},
    "BSHBSelect__916555373": {},
    "BSHBSelect__1705598040": {},
    "BaseRichTextJson": {
      "blocks": [
        74
      ],
      "content": [
        12
      ],
      "toc": [
        13
      ],
      "__typename": [
        74
      ]
    },
    "BlockAudio": {
      "fileName": [
        74
      ],
      "fileSize": [
        54
      ],
      "lastModified": [
        49
      ],
      "mimeType": [
        74
      ],
      "url": [
        74
      ],
      "__typename": [
        74
      ]
    },
    "BlockCodeSnippet": {
      "allowedLanguages": [
        43
      ],
      "code": [
        74
      ],
      "html": [
        74,
        {
          "theme": [
            74
          ]
        }
      ],
      "language": [
        43
      ],
      "__typename": [
        74
      ]
    },
    "BlockColor": {
      "b": [
        54
      ],
      "g": [
        54
      ],
      "hex": [
        74
      ],
      "hsl": [
        74
      ],
      "r": [
        54
      ],
      "rgb": [
        74
      ],
      "__typename": [
        74
      ]
    },
    "BlockDocument": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "on_Articles": [
        1
      ],
      "on_ArticlesItem": [
        2
      ],
      "on_Authors": [
        7
      ],
      "on_AuthorsItem": [
        8
      ],
      "on_CalloutComponent": [
        37
      ],
      "on_Categories": [
        38
      ],
      "on_CategoriesItem": [
        39
      ],
      "on_CategoriesSection": [
        42
      ],
      "on_Components": [
        44
      ],
      "on_Index": [
        52
      ],
      "on_InlineIconComponent": [
        53
      ],
      "on_MetadataComponent": [
        58
      ],
      "on_NavLinks": [
        60
      ],
      "on_NavLinksItem": [
        61
      ],
      "on_PopularArticlesSection": [
        65
      ],
      "on_Settings": [
        69
      ],
      "on_SocialMediaLinks": [
        70
      ],
      "on_SocialMediaLinksItem": [
        71
      ],
      "on_Theme": [
        79
      ],
      "__typename": [
        74
      ]
    },
    "BlockDocumentSys": {
      "apiNamePath": [
        74
      ],
      "createdAt": [
        74
      ],
      "hash": [
        74
      ],
      "id": [
        51
      ],
      "idPath": [
        74
      ],
      "lastModifiedAt": [
        74
      ],
      "slug": [
        74
      ],
      "slugPath": [
        74
      ],
      "title": [
        74
      ],
      "__typename": [
        74
      ]
    },
    "BlockFile": {
      "fileName": [
        74
      ],
      "fileSize": [
        54
      ],
      "lastModified": [
        49
      ],
      "mimeType": [
        74
      ],
      "url": [
        74
      ],
      "__typename": [
        74
      ]
    },
    "BlockImage": {
      "alt": [
        74
      ],
      "aspectRatio": [
        74
      ],
      "blurDataURL": [
        74
      ],
      "fileName": [
        74
      ],
      "fileSize": [
        54
      ],
      "height": [
        54
      ],
      "lastModified": [
        49
      ],
      "mimeType": [
        74
      ],
      "placeholderURL": [
        74
      ],
      "rawUrl": [
        74
      ],
      "thumbhash": [
        74
      ],
      "url": [
        74,
        {
          "anim": [
            74
          ],
          "background": [
            74
          ],
          "blur": [
            54
          ],
          "border": [
            74
          ],
          "brightness": [
            54
          ],
          "compression": [
            74
          ],
          "contrast": [
            54
          ],
          "dpr": [
            54
          ],
          "fit": [
            74
          ],
          "format": [
            74
          ],
          "gamma": [
            74
          ],
          "gravity": [
            74
          ],
          "height": [
            54
          ],
          "metadata": [
            74
          ],
          "quality": [
            54
          ],
          "rotate": [
            74
          ],
          "sharpen": [
            74
          ],
          "trim": [
            74
          ],
          "width": [
            54
          ]
        }
      ],
      "width": [
        54
      ],
      "__typename": [
        74
      ]
    },
    "BlockList": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_meta": [
        57
      ],
      "_searchKey": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "on_Articles": [
        1
      ],
      "on_Authors": [
        7
      ],
      "on_Categories": [
        38
      ],
      "on_NavLinks": [
        60
      ],
      "on_SocialMediaLinks": [
        70
      ],
      "__typename": [
        74
      ]
    },
    "BlockOgImage": {
      "url": [
        74
      ],
      "__typename": [
        74
      ]
    },
    "BlockRichText": {
      "html": [
        74,
        {
          "slugs": [
            36
          ],
          "toc": [
            36
          ]
        }
      ],
      "json": [
        68
      ],
      "markdown": [
        74
      ],
      "plainText": [
        74
      ],
      "readingTime": [
        54,
        {
          "wpm": [
            54
          ]
        }
      ],
      "on_Body": [
        34
      ],
      "on_Content": [
        45
      ],
      "on_Subtitle": [
        77
      ],
      "__typename": [
        74
      ]
    },
    "BlockVideo": {
      "aspectRatio": [
        74
      ],
      "duration": [
        49
      ],
      "fileName": [
        74
      ],
      "fileSize": [
        54
      ],
      "height": [
        54
      ],
      "lastModified": [
        49
      ],
      "mimeType": [
        74
      ],
      "url": [
        74
      ],
      "width": [
        54
      ],
      "__typename": [
        74
      ]
    },
    "Body": {
      "html": [
        74,
        {
          "slugs": [
            36
          ],
          "toc": [
            36
          ]
        }
      ],
      "json": [
        35
      ],
      "markdown": [
        74
      ],
      "plainText": [
        74
      ],
      "readingTime": [
        54,
        {
          "wpm": [
            54
          ]
        }
      ],
      "__typename": [
        74
      ]
    },
    "BodyRichText": {
      "blocks": [
        82
      ],
      "content": [
        12
      ],
      "toc": [
        13
      ],
      "__typename": [
        74
      ]
    },
    "Boolean": {},
    "CalloutComponent": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "content": [
        45
      ],
      "type": [
        17
      ],
      "__typename": [
        74
      ]
    },
    "Categories": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_meta": [
        57
      ],
      "_searchKey": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "item": [
        39
      ],
      "items": [
        39
      ],
      "__typename": [
        74
      ]
    },
    "CategoriesItem": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "articles": [
        1,
        {
          "filter": [
            3
          ],
          "first": [
            54
          ],
          "orderBy": [
            6
          ],
          "skip": [
            54
          ]
        }
      ],
      "description": [
        74
      ],
      "icon": [
        74
      ],
      "ogImage": [
        31
      ],
      "__typename": [
        74
      ]
    },
    "CategoriesItemFilterInput": {
      "AND": [
        40
      ],
      "OR": [
        40
      ],
      "_sys_apiNamePath": [
        75
      ],
      "_sys_createdAt": [
        47
      ],
      "_sys_hash": [
        75
      ],
      "_sys_id": [
        75
      ],
      "_sys_idPath": [
        75
      ],
      "_sys_lastModifiedAt": [
        47
      ],
      "_sys_slug": [
        75
      ],
      "_sys_slugPath": [
        75
      ],
      "_sys_title": [
        75
      ],
      "articles": [
        56
      ],
      "description": [
        75
      ],
      "icon": [
        75
      ],
      "__typename": [
        74
      ]
    },
    "CategoriesItemOrderByEnum": {},
    "CategoriesSection": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "categories": [
        38,
        {
          "filter": [
            40
          ],
          "first": [
            54
          ],
          "orderBy": [
            41
          ],
          "skip": [
            54
          ]
        }
      ],
      "title": [
        74
      ],
      "__typename": [
        74
      ]
    },
    "CodeSnippetLanguage": {},
    "Components": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "__typename": [
        74
      ]
    },
    "Content": {
      "html": [
        74,
        {
          "slugs": [
            36
          ],
          "toc": [
            36
          ]
        }
      ],
      "json": [
        46
      ],
      "markdown": [
        74
      ],
      "plainText": [
        74
      ],
      "readingTime": [
        54,
        {
          "wpm": [
            54
          ]
        }
      ],
      "__typename": [
        74
      ]
    },
    "ContentRichText": {
      "content": [
        12
      ],
      "toc": [
        13
      ],
      "__typename": [
        74
      ]
    },
    "DateFilter": {
      "eq": [
        48
      ],
      "isAfter": [
        48
      ],
      "isBefore": [
        48
      ],
      "neq": [
        48
      ],
      "onOrAfter": [
        48
      ],
      "onOrBefore": [
        48
      ],
      "__typename": [
        74
      ]
    },
    "DateTime": {},
    "Float": {},
    "GetUploadSignedURL": {
      "signedURL": [
        74
      ],
      "uploadURL": [
        74
      ],
      "__typename": [
        74
      ]
    },
    "ID": {},
    "Index": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "categoriesSection": [
        42
      ],
      "greeting": [
        74
      ],
      "popularArticlesSection": [
        65
      ],
      "rights": [
        74
      ],
      "socialMediaLinks": [
        70,
        {
          "filter": [
            72
          ],
          "first": [
            54
          ],
          "orderBy": [
            73
          ],
          "skip": [
            54
          ]
        }
      ],
      "subtitle": [
        77
      ],
      "__typename": [
        74
      ]
    },
    "InlineIconComponent": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "name": [
        74
      ],
      "tooltip": [
        74
      ],
      "__typename": [
        74
      ]
    },
    "Int": {},
    "JSON": {},
    "ListFilter": {
      "isEmpty": [
        36
      ],
      "length": [
        54
      ],
      "__typename": [
        74
      ]
    },
    "ListMeta": {
      "totalCount": [
        54
      ],
      "__typename": [
        74
      ]
    },
    "MetadataComponent": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "description": [
        74
      ],
      "icon": [
        29
      ],
      "ogImage": [
        31
      ],
      "title": [
        74
      ],
      "__typename": [
        74
      ]
    },
    "Mutation": {
      "getUploadSignedURL": [
        50,
        {
          "fileHash": [
            74
          ],
          "fileName": [
            74,
            "String!"
          ]
        }
      ],
      "transaction": [
        74,
        {
          "autoCommit": [
            74
          ],
          "data": [
            74,
            "String!"
          ],
          "skipWorkflows": [
            36
          ]
        }
      ],
      "transactionAwaitable": [
        80,
        {
          "autoCommit": [
            74
          ],
          "data": [
            74,
            "String!"
          ],
          "skipWorkflows": [
            36
          ],
          "timeout": [
            54
          ]
        }
      ],
      "transactionStatus": [
        80,
        {
          "id": [
            74,
            "String!"
          ]
        }
      ],
      "__typename": [
        74
      ]
    },
    "NavLinks": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_meta": [
        57
      ],
      "_searchKey": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "item": [
        61
      ],
      "items": [
        61
      ],
      "__typename": [
        74
      ]
    },
    "NavLinksItem": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "href": [
        74
      ],
      "__typename": [
        74
      ]
    },
    "NavLinksItemFilterInput": {
      "AND": [
        62
      ],
      "OR": [
        62
      ],
      "_sys_apiNamePath": [
        75
      ],
      "_sys_createdAt": [
        47
      ],
      "_sys_hash": [
        75
      ],
      "_sys_id": [
        75
      ],
      "_sys_idPath": [
        75
      ],
      "_sys_lastModifiedAt": [
        47
      ],
      "_sys_slug": [
        75
      ],
      "_sys_slugPath": [
        75
      ],
      "_sys_title": [
        75
      ],
      "href": [
        75
      ],
      "__typename": [
        74
      ]
    },
    "NavLinksItemOrderByEnum": {},
    "NumberFilter": {
      "eq": [
        49
      ],
      "gt": [
        49
      ],
      "gte": [
        49
      ],
      "lt": [
        49
      ],
      "lte": [
        49
      ],
      "neq": [
        49
      ],
      "__typename": [
        74
      ]
    },
    "PopularArticlesSection": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "articles": [
        2
      ],
      "title": [
        74
      ],
      "__typename": [
        74
      ]
    },
    "Query": {
      "_componentInstances": [
        84
      ],
      "_sys": [
        67
      ],
      "authors": [
        7,
        {
          "filter": [
            9
          ],
          "first": [
            54
          ],
          "orderBy": [
            10
          ],
          "skip": [
            54
          ]
        }
      ],
      "components": [
        44
      ],
      "index": [
        52
      ],
      "settings": [
        69
      ],
      "__typename": [
        74
      ]
    },
    "RepoSys": {
      "hash": [
        74
      ],
      "id": [
        51
      ],
      "slug": [
        74
      ],
      "title": [
        74
      ],
      "__typename": [
        74
      ]
    },
    "RichTextJson": {
      "content": [
        12
      ],
      "toc": [
        13
      ],
      "on_BaseRichTextJson": [
        22
      ],
      "on_BodyRichText": [
        35
      ],
      "on_ContentRichText": [
        46
      ],
      "on_SubtitleRichText": [
        78
      ],
      "__typename": [
        74
      ]
    },
    "Settings": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "intercomAppId": [
        74
      ],
      "logo": [
        29
      ],
      "logoLightMode": [
        29
      ],
      "metadata": [
        58
      ],
      "navLinks": [
        60,
        {
          "filter": [
            62
          ],
          "first": [
            54
          ],
          "orderBy": [
            63
          ],
          "skip": [
            54
          ]
        }
      ],
      "showUseTemplate": [
        36
      ],
      "theme": [
        79
      ],
      "__typename": [
        74
      ]
    },
    "SocialMediaLinks": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_meta": [
        57
      ],
      "_searchKey": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "item": [
        71
      ],
      "items": [
        71
      ],
      "__typename": [
        74
      ]
    },
    "SocialMediaLinksItem": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "platform": [
        19
      ],
      "url": [
        74
      ],
      "__typename": [
        74
      ]
    },
    "SocialMediaLinksItemFilterInput": {
      "AND": [
        72
      ],
      "OR": [
        72
      ],
      "_sys_apiNamePath": [
        75
      ],
      "_sys_createdAt": [
        47
      ],
      "_sys_hash": [
        75
      ],
      "_sys_id": [
        75
      ],
      "_sys_idPath": [
        75
      ],
      "_sys_lastModifiedAt": [
        47
      ],
      "_sys_slug": [
        75
      ],
      "_sys_slugPath": [
        75
      ],
      "_sys_title": [
        75
      ],
      "url": [
        75
      ],
      "__typename": [
        74
      ]
    },
    "SocialMediaLinksItemOrderByEnum": {},
    "String": {},
    "StringFilter": {
      "contains": [
        74
      ],
      "endsWith": [
        74
      ],
      "eq": [
        74
      ],
      "matches": [
        76
      ],
      "notEq": [
        74
      ],
      "startsWith": [
        74
      ],
      "__typename": [
        74
      ]
    },
    "StringMatchesFilter": {
      "caseSensitive": [
        36
      ],
      "pattern": [
        74
      ],
      "__typename": [
        74
      ]
    },
    "Subtitle": {
      "html": [
        74,
        {
          "slugs": [
            36
          ],
          "toc": [
            36
          ]
        }
      ],
      "json": [
        78
      ],
      "markdown": [
        74
      ],
      "plainText": [
        74
      ],
      "readingTime": [
        54,
        {
          "wpm": [
            54
          ]
        }
      ],
      "__typename": [
        74
      ]
    },
    "SubtitleRichText": {
      "content": [
        12
      ],
      "toc": [
        13
      ],
      "__typename": [
        74
      ]
    },
    "Theme": {
      "_analyticsKey": [
        74,
        {
          "scope": [
            0
          ]
        }
      ],
      "_id": [
        74
      ],
      "_idPath": [
        74
      ],
      "_slug": [
        74
      ],
      "_slugPath": [
        74
      ],
      "_sys": [
        27
      ],
      "_title": [
        74
      ],
      "accentColor": [
        16
      ],
      "appearance": [
        15
      ],
      "grayScale": [
        18
      ],
      "panelBackground": [
        21
      ],
      "radius": [
        14
      ],
      "scaling": [
        20
      ],
      "__typename": [
        74
      ]
    },
    "TransactionStatus": {
      "duration": [
        54
      ],
      "endedAt": [
        74
      ],
      "id": [
        74
      ],
      "message": [
        74
      ],
      "startedAt": [
        74
      ],
      "status": [
        81
      ],
      "__typename": [
        74
      ]
    },
    "TransactionStatusEnum": {},
    "UnionCalloutComponentInlineIconComponent": {
      "on_CalloutComponent": [
        37
      ],
      "on_InlineIconComponent": [
        53
      ],
      "on_BlockDocument": [
        26
      ],
      "__typename": [
        74
      ]
    },
    "Variant": {
      "apiName": [
        74
      ],
      "color": [
        74
      ],
      "id": [
        74
      ],
      "isDefault": [
        36
      ],
      "label": [
        74
      ],
      "__typename": [
        74
      ]
    },
    "_components": {
      "articlesItem": [
        1,
        {
          "filter": [
            3
          ],
          "first": [
            54
          ],
          "orderBy": [
            6
          ],
          "skip": [
            54
          ]
        }
      ],
      "authorsItem": [
        7,
        {
          "filter": [
            9
          ],
          "first": [
            54
          ],
          "orderBy": [
            10
          ],
          "skip": [
            54
          ]
        }
      ],
      "categoriesItem": [
        38,
        {
          "filter": [
            40
          ],
          "first": [
            54
          ],
          "orderBy": [
            41
          ],
          "skip": [
            54
          ]
        }
      ],
      "navLinksItem": [
        60,
        {
          "filter": [
            62
          ],
          "first": [
            54
          ],
          "orderBy": [
            63
          ],
          "skip": [
            54
          ]
        }
      ],
      "socialMediaLinksItem": [
        70,
        {
          "filter": [
            72
          ],
          "first": [
            54
          ],
          "orderBy": [
            73
          ],
          "skip": [
            54
          ]
        }
      ],
      "__typename": [
        74
      ]
    }
  }
};

// .basehub/schema.ts
function fragmentOn(name, fields) {
  return { __fragmentOn: name, ...fields };
}
function fragmentOnRecursiveCollection(name, fields, options) {
  let current = {
    ...fields
  };
  if (options.levels > 0) {
    current[options.recursiveKey] = {
      ...options.getLevelArgs ? { __args: options.getLevelArgs(options.levels) } : {},
      items: fragmentOnRecursiveCollection(name, fields, {
        ...options,
        levels: options.levels - 1
      })
    };
  }
  return current;
}

// .basehub/index.ts
var typeMap = linkTypeMap(types_default);
var createClient2 = function(options) {
  const { url, headers } = getStuffFromEnv(options);
  return createClient({
    url: url.toString(),
    ...options,
    headers: { ...options?.headers, ...headers },
    queryRoot: typeMap.Query,
    mutationRoot: typeMap.Mutation,
    subscriptionRoot: typeMap.Subscription
  });
};
var everything = {
  __scalar: true
};
var generateQueryOp = function(fields) {
  return generateGraphqlOperation("query", typeMap.Query, fields);
};
var generateMutationOp = function(fields) {
  return generateGraphqlOperation("mutation", typeMap.Mutation, fields);
};
var getStuffFromEnv = (options) => {
  const defaultEnvVarPrefix = "BASEHUB";
  options = options || {};
  if (options.token === void 0) {
    options.token = null;
  }
  if (options.prefix === void 0) {
    options.prefix = null;
  }
  if (!options.draft && false) {
    options.draft = true;
  }
  const buildEnvVarName = (name) => {
    let prefix = defaultEnvVarPrefix;
    if (options.prefix) {
      if (options.prefix.endsWith("_")) {
        options.prefix = options.prefix.slice(0, -1);
      }
      if (options.prefix.endsWith(name)) {
        options.prefix = options.prefix.slice(0, -name.length);
      }
      if (options.prefix.endsWith(defaultEnvVarPrefix)) {
        prefix = options.prefix;
      } else {
        prefix = `${options.prefix}_${defaultEnvVarPrefix}`;
      }
    }
    return `${prefix}_${name}`;
  };
  const getEnvVar = (name) => process.env[buildEnvVarName(name)];
  const parsedDebugForcedURL = getEnvVar("DEBUG_FORCED_URL");
  const parsedBackwardsCompatURL = getEnvVar("URL");
  const backwardsCompatURL = parsedBackwardsCompatURL ? new URL(parsedBackwardsCompatURL) : void 0;
  const basehubUrl = new URL(
    parsedDebugForcedURL ? parsedDebugForcedURL : `https://api.basehub.com/graphql`
  );
  const parsedBasehubTokenEnv = getEnvVar("TOKEN");
  const parsedBasehubRefEnv = getEnvVar("REF");
  const parsedBasehubDraftEnv = getEnvVar("DRAFT");
  const parsedBasehubApiVersionEnv = getEnvVar("API_VERSION");
  let tokenNotFoundErrorMessage = `\u{1F534} Token not found. Make sure to include the ${buildEnvVarName(
    "TOKEN"
  )} env var.`;
  const resolveTokenParam = (token2) => {
    if (!token2)
      return null;
    const isRaw = token2.startsWith("bshb_");
    if (isRaw)
      return token2;
    tokenNotFoundErrorMessage = `\u{1F534} Token not found. Make sure to include the ${token2} env var.`;
    return process.env[token2] ?? "";
  };
  const resolvedToken = resolveTokenParam(options?.token ?? null);
  const token = resolvedToken ?? basehubUrl.searchParams.get("token") ?? parsedBasehubTokenEnv ?? (backwardsCompatURL ? backwardsCompatURL.searchParams.get("token") : void 0) ?? null;
  if (!token) {
    throw new Error(tokenNotFoundErrorMessage);
  }
  let draft = basehubUrl.searchParams.get("draft") ?? parsedBasehubDraftEnv ?? (backwardsCompatURL ? backwardsCompatURL.searchParams.get("draft") : void 0) ?? false;
  if (options?.draft !== void 0) {
    draft = options.draft;
  }
  let apiVersion = basehubUrl.searchParams.get("api-version") ?? parsedBasehubApiVersionEnv ?? (backwardsCompatURL ? backwardsCompatURL.searchParams.get("api-version") : void 0) ?? "2";
  if (options?.apiVersion !== void 0) {
    apiVersion = options.apiVersion;
  }
  if (basehubUrl.pathname.split("/")[1] !== "graphql") {
    throw new Error(`\u{1F534} Invalid URL. The URL needs to point your repo's GraphQL endpoint, so the pathname should end with /graphql.`);
  }
  basehubUrl.searchParams.delete("token");
  basehubUrl.searchParams.delete("ref");
  basehubUrl.searchParams.delete("draft");
  basehubUrl.searchParams.delete("api-version");
  const gitBranch = "main";
  const gitCommitSHA = "ad33c9b65dff2c958b93dbd8c708d6517f44f931";
  return {
    isForcedDraft: false,
    draft,
    url: basehubUrl,
    headers: {
      "x-basehub-token": token,
      "x-basehub-ref": resolvedRef.ref,
      ...gitBranch ? { "x-basehub-git-branch": gitBranch } : {},
      ...gitCommitSHA ? { "x-basehub-git-commit-sha": gitCommitSHA } : {},
      ...gitBranchDeploymentURL ? { "x-basehub-git-branch-deployment-url": gitBranchDeploymentURL } : {},
      ...productionDeploymentURL ? { "x-basehub-production-deployment-url": productionDeploymentURL } : {},
      ...draft ? { "x-basehub-draft": "true" } : {},
      ...apiVersion ? { "x-basehub-api-version": apiVersion } : {}
    }
  };
};
var sdkBuildId = "bshb_sdk_3bc64c2e75756";
var resolvedRef = { "repoHash": "a6462053", "type": "branch", "ref": "main", "createSuggestedBranchLink": null, "id": "PKEXwGZsp0nxpBNHdM4k0", "name": "main", "git": null, "createdAt": "2024-12-10T07:36:06.692Z", "archivedAt": null, "archivedBy": null, "headCommitId": "wa3drJhtWJfNdZzz6oYhO", "isDefault": true, "workingRootBlockId": "NcmtyUizMfzDtonoYjAx0" };
var gitBranchDeploymentURL = null;
var productionDeploymentURL = null;
function hashObject(obj) {
  const sortObjectKeys = (obj2) => {
    if (!isObjectAsWeCommonlyCallIt(obj2))
      return obj2;
    return Object.keys(obj2).sort().reduce((acc, key) => {
      acc[key] = obj2[key];
      return acc;
    }, {});
  };
  const recursiveSortObjectKeys = (obj2) => {
    const sortedObj2 = sortObjectKeys(obj2);
    if (!isObjectAsWeCommonlyCallIt(sortedObj2))
      return sortedObj2;
    Object.keys(sortedObj2).forEach((key) => {
      if (isObjectAsWeCommonlyCallIt(sortedObj2[key])) {
        sortedObj2[key] = recursiveSortObjectKeys(
          sortedObj2[key]
        );
      } else if (Array.isArray(sortedObj2[key])) {
        sortedObj2[key] = sortedObj2[key].map(
          (item) => {
            if (isObjectAsWeCommonlyCallIt(item)) {
              return recursiveSortObjectKeys(item);
            } else {
              return item;
            }
          }
        );
      }
    });
    return sortedObj2;
  };
  const isObjectAsWeCommonlyCallIt = (obj2) => {
    return Object.prototype.toString.call(obj2) === "[object Object]";
  };
  const sortedObj = recursiveSortObjectKeys(obj);
  const str = JSON.stringify(sortedObj);
  let hash = 0;
  for (let i = 0, len = str.length; i < len; i++) {
    let chr = str.charCodeAt(i);
    hash = (hash << 5) - hash + chr;
    hash |= 0;
  }
  return Math.abs(hash).toString();
}
function cacheTagFromQuery(query) {
  const now = performance.now();
  const result = "basehub-" + hashObject({ ...query, refId: resolvedRef.id });
  return result;
}
var basehub = (options) => {
  const { url, headers } = getStuffFromEnv(options);
  if (!options) {
    options = {};
  }
  options.getExtraFetchOptions = (op, _body, originalRequest) => {
    if (op !== "query")
      return {};
    if (false)
      return {};
    if (typeof options?.next !== "undefined")
      return {};
    const cacheTag = cacheTagFromQuery(originalRequest);
    return { next: { tags: [cacheTag] }, headers: { "x-basehub-sdk-build-id": "bshb_sdk_3bc64c2e75756", "x-basehub-cache-tag": cacheTag } };
  };
  return {
    ...createClient2(options),
    raw: createFetcher({ ...options, url, headers })
  };
};
basehub.replaceSystemAliases = createClient.replaceSystemAliases;
export {
  GenqlError,
  basehub,
  cacheTagFromQuery,
  everything,
  fragmentOn,
  fragmentOnRecursiveCollection,
  generateMutationOp,
  generateQueryOp,
  getStuffFromEnv,
  gitBranchDeploymentURL,
  productionDeploymentURL,
  resolvedRef,
  sdkBuildId
};
