// This file was generated by basehub. Do not edit directly. Read more: https://basehub.com/docs/api-reference/basehub-sdk

/* eslint-disable */
/* eslint-disable eslint-comments/no-restricted-disable */
/* tslint:disable */
// @ts-nocheck

export default {
    "scalars": [
        0,
        6,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        36,
        41,
        43,
        48,
        49,
        51,
        54,
        55,
        63,
        73,
        74,
        81
    ],
    "types": {
        "AnalyticsKeyScope": {},
        "Articles": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_meta": [
                57
            ],
            "_searchKey": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "item": [
                2
            ],
            "items": [
                2
            ],
            "__typename": [
                74
            ]
        },
        "ArticlesItem": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "author": [
                8
            ],
            "body": [
                34
            ],
            "excerpt": [
                74
            ],
            "ogImage": [
                31
            ],
            "related": [
                2
            ],
            "__typename": [
                74
            ]
        },
        "ArticlesItemFilterInput": {
            "AND": [
                3
            ],
            "OR": [
                3
            ],
            "_sys_apiNamePath": [
                75
            ],
            "_sys_createdAt": [
                47
            ],
            "_sys_hash": [
                75
            ],
            "_sys_id": [
                75
            ],
            "_sys_idPath": [
                75
            ],
            "_sys_lastModifiedAt": [
                47
            ],
            "_sys_slug": [
                75
            ],
            "_sys_slugPath": [
                75
            ],
            "_sys_title": [
                75
            ],
            "author": [
                4
            ],
            "excerpt": [
                75
            ],
            "related": [
                5
            ],
            "__typename": [
                74
            ]
        },
        "ArticlesItemFilterInput__author_0___untitled": {
            "_sys_apiNamePath": [
                75
            ],
            "_sys_createdAt": [
                47
            ],
            "_sys_hash": [
                75
            ],
            "_sys_id": [
                75
            ],
            "_sys_idPath": [
                75
            ],
            "_sys_lastModifiedAt": [
                47
            ],
            "_sys_slug": [
                75
            ],
            "_sys_slugPath": [
                75
            ],
            "_sys_title": [
                75
            ],
            "xProfile": [
                75
            ],
            "__typename": [
                74
            ]
        },
        "ArticlesItemFilterInput__related_0___untitled": {
            "_sys_apiNamePath": [
                75
            ],
            "_sys_createdAt": [
                47
            ],
            "_sys_hash": [
                75
            ],
            "_sys_id": [
                75
            ],
            "_sys_idPath": [
                75
            ],
            "_sys_lastModifiedAt": [
                47
            ],
            "_sys_slug": [
                75
            ],
            "_sys_slugPath": [
                75
            ],
            "_sys_title": [
                75
            ],
            "excerpt": [
                75
            ],
            "__typename": [
                74
            ]
        },
        "ArticlesItemOrderByEnum": {},
        "Authors": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_meta": [
                57
            ],
            "_searchKey": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "item": [
                8
            ],
            "items": [
                8
            ],
            "__typename": [
                74
            ]
        },
        "AuthorsItem": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "avatar": [
                29
            ],
            "xProfile": [
                74
            ],
            "__typename": [
                74
            ]
        },
        "AuthorsItemFilterInput": {
            "AND": [
                9
            ],
            "OR": [
                9
            ],
            "_sys_apiNamePath": [
                75
            ],
            "_sys_createdAt": [
                47
            ],
            "_sys_hash": [
                75
            ],
            "_sys_id": [
                75
            ],
            "_sys_idPath": [
                75
            ],
            "_sys_lastModifiedAt": [
                47
            ],
            "_sys_slug": [
                75
            ],
            "_sys_slugPath": [
                75
            ],
            "_sys_title": [
                75
            ],
            "xProfile": [
                75
            ],
            "__typename": [
                74
            ]
        },
        "AuthorsItemOrderByEnum": {},
        "BSHBEventSchema": {},
        "BSHBRichTextContentSchema": {},
        "BSHBRichTextTOCSchema": {},
        "BSHBSelect_83162882": {},
        "BSHBSelect_337363946": {},
        "BSHBSelect_893959412": {},
        "BSHBSelect_2084155347": {},
        "BSHBSelect_2125218645": {},
        "BSHBSelect__669079093": {},
        "BSHBSelect__916555373": {},
        "BSHBSelect__1705598040": {},
        "BaseRichTextJson": {
            "blocks": [
                74
            ],
            "content": [
                12
            ],
            "toc": [
                13
            ],
            "__typename": [
                74
            ]
        },
        "BlockAudio": {
            "fileName": [
                74
            ],
            "fileSize": [
                54
            ],
            "lastModified": [
                49
            ],
            "mimeType": [
                74
            ],
            "url": [
                74
            ],
            "__typename": [
                74
            ]
        },
        "BlockCodeSnippet": {
            "allowedLanguages": [
                43
            ],
            "code": [
                74
            ],
            "html": [
                74,
                {
                    "theme": [
                        74
                    ]
                }
            ],
            "language": [
                43
            ],
            "__typename": [
                74
            ]
        },
        "BlockColor": {
            "b": [
                54
            ],
            "g": [
                54
            ],
            "hex": [
                74
            ],
            "hsl": [
                74
            ],
            "r": [
                54
            ],
            "rgb": [
                74
            ],
            "__typename": [
                74
            ]
        },
        "BlockDocument": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "on_Articles": [
                1
            ],
            "on_ArticlesItem": [
                2
            ],
            "on_Authors": [
                7
            ],
            "on_AuthorsItem": [
                8
            ],
            "on_CalloutComponent": [
                37
            ],
            "on_Categories": [
                38
            ],
            "on_CategoriesItem": [
                39
            ],
            "on_CategoriesSection": [
                42
            ],
            "on_Components": [
                44
            ],
            "on_Index": [
                52
            ],
            "on_InlineIconComponent": [
                53
            ],
            "on_MetadataComponent": [
                58
            ],
            "on_NavLinks": [
                60
            ],
            "on_NavLinksItem": [
                61
            ],
            "on_PopularArticlesSection": [
                65
            ],
            "on_Settings": [
                69
            ],
            "on_SocialMediaLinks": [
                70
            ],
            "on_SocialMediaLinksItem": [
                71
            ],
            "on_Theme": [
                79
            ],
            "__typename": [
                74
            ]
        },
        "BlockDocumentSys": {
            "apiNamePath": [
                74
            ],
            "createdAt": [
                74
            ],
            "hash": [
                74
            ],
            "id": [
                51
            ],
            "idPath": [
                74
            ],
            "lastModifiedAt": [
                74
            ],
            "slug": [
                74
            ],
            "slugPath": [
                74
            ],
            "title": [
                74
            ],
            "__typename": [
                74
            ]
        },
        "BlockFile": {
            "fileName": [
                74
            ],
            "fileSize": [
                54
            ],
            "lastModified": [
                49
            ],
            "mimeType": [
                74
            ],
            "url": [
                74
            ],
            "__typename": [
                74
            ]
        },
        "BlockImage": {
            "alt": [
                74
            ],
            "aspectRatio": [
                74
            ],
            "blurDataURL": [
                74
            ],
            "fileName": [
                74
            ],
            "fileSize": [
                54
            ],
            "height": [
                54
            ],
            "lastModified": [
                49
            ],
            "mimeType": [
                74
            ],
            "placeholderURL": [
                74
            ],
            "rawUrl": [
                74
            ],
            "thumbhash": [
                74
            ],
            "url": [
                74,
                {
                    "anim": [
                        74
                    ],
                    "background": [
                        74
                    ],
                    "blur": [
                        54
                    ],
                    "border": [
                        74
                    ],
                    "brightness": [
                        54
                    ],
                    "compression": [
                        74
                    ],
                    "contrast": [
                        54
                    ],
                    "dpr": [
                        54
                    ],
                    "fit": [
                        74
                    ],
                    "format": [
                        74
                    ],
                    "gamma": [
                        74
                    ],
                    "gravity": [
                        74
                    ],
                    "height": [
                        54
                    ],
                    "metadata": [
                        74
                    ],
                    "quality": [
                        54
                    ],
                    "rotate": [
                        74
                    ],
                    "sharpen": [
                        74
                    ],
                    "trim": [
                        74
                    ],
                    "width": [
                        54
                    ]
                }
            ],
            "width": [
                54
            ],
            "__typename": [
                74
            ]
        },
        "BlockList": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_meta": [
                57
            ],
            "_searchKey": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "on_Articles": [
                1
            ],
            "on_Authors": [
                7
            ],
            "on_Categories": [
                38
            ],
            "on_NavLinks": [
                60
            ],
            "on_SocialMediaLinks": [
                70
            ],
            "__typename": [
                74
            ]
        },
        "BlockOgImage": {
            "url": [
                74
            ],
            "__typename": [
                74
            ]
        },
        "BlockRichText": {
            "html": [
                74,
                {
                    "slugs": [
                        36
                    ],
                    "toc": [
                        36
                    ]
                }
            ],
            "json": [
                68
            ],
            "markdown": [
                74
            ],
            "plainText": [
                74
            ],
            "readingTime": [
                54,
                {
                    "wpm": [
                        54
                    ]
                }
            ],
            "on_Body": [
                34
            ],
            "on_Content": [
                45
            ],
            "on_Subtitle": [
                77
            ],
            "__typename": [
                74
            ]
        },
        "BlockVideo": {
            "aspectRatio": [
                74
            ],
            "duration": [
                49
            ],
            "fileName": [
                74
            ],
            "fileSize": [
                54
            ],
            "height": [
                54
            ],
            "lastModified": [
                49
            ],
            "mimeType": [
                74
            ],
            "url": [
                74
            ],
            "width": [
                54
            ],
            "__typename": [
                74
            ]
        },
        "Body": {
            "html": [
                74,
                {
                    "slugs": [
                        36
                    ],
                    "toc": [
                        36
                    ]
                }
            ],
            "json": [
                35
            ],
            "markdown": [
                74
            ],
            "plainText": [
                74
            ],
            "readingTime": [
                54,
                {
                    "wpm": [
                        54
                    ]
                }
            ],
            "__typename": [
                74
            ]
        },
        "BodyRichText": {
            "blocks": [
                82
            ],
            "content": [
                12
            ],
            "toc": [
                13
            ],
            "__typename": [
                74
            ]
        },
        "Boolean": {},
        "CalloutComponent": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "content": [
                45
            ],
            "type": [
                17
            ],
            "__typename": [
                74
            ]
        },
        "Categories": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_meta": [
                57
            ],
            "_searchKey": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "item": [
                39
            ],
            "items": [
                39
            ],
            "__typename": [
                74
            ]
        },
        "CategoriesItem": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "articles": [
                1,
                {
                    "filter": [
                        3
                    ],
                    "first": [
                        54
                    ],
                    "orderBy": [
                        6
                    ],
                    "skip": [
                        54
                    ]
                }
            ],
            "description": [
                74
            ],
            "icon": [
                74
            ],
            "ogImage": [
                31
            ],
            "__typename": [
                74
            ]
        },
        "CategoriesItemFilterInput": {
            "AND": [
                40
            ],
            "OR": [
                40
            ],
            "_sys_apiNamePath": [
                75
            ],
            "_sys_createdAt": [
                47
            ],
            "_sys_hash": [
                75
            ],
            "_sys_id": [
                75
            ],
            "_sys_idPath": [
                75
            ],
            "_sys_lastModifiedAt": [
                47
            ],
            "_sys_slug": [
                75
            ],
            "_sys_slugPath": [
                75
            ],
            "_sys_title": [
                75
            ],
            "articles": [
                56
            ],
            "description": [
                75
            ],
            "icon": [
                75
            ],
            "__typename": [
                74
            ]
        },
        "CategoriesItemOrderByEnum": {},
        "CategoriesSection": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "categories": [
                38,
                {
                    "filter": [
                        40
                    ],
                    "first": [
                        54
                    ],
                    "orderBy": [
                        41
                    ],
                    "skip": [
                        54
                    ]
                }
            ],
            "title": [
                74
            ],
            "__typename": [
                74
            ]
        },
        "CodeSnippetLanguage": {},
        "Components": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "__typename": [
                74
            ]
        },
        "Content": {
            "html": [
                74,
                {
                    "slugs": [
                        36
                    ],
                    "toc": [
                        36
                    ]
                }
            ],
            "json": [
                46
            ],
            "markdown": [
                74
            ],
            "plainText": [
                74
            ],
            "readingTime": [
                54,
                {
                    "wpm": [
                        54
                    ]
                }
            ],
            "__typename": [
                74
            ]
        },
        "ContentRichText": {
            "content": [
                12
            ],
            "toc": [
                13
            ],
            "__typename": [
                74
            ]
        },
        "DateFilter": {
            "eq": [
                48
            ],
            "isAfter": [
                48
            ],
            "isBefore": [
                48
            ],
            "neq": [
                48
            ],
            "onOrAfter": [
                48
            ],
            "onOrBefore": [
                48
            ],
            "__typename": [
                74
            ]
        },
        "DateTime": {},
        "Float": {},
        "GetUploadSignedURL": {
            "signedURL": [
                74
            ],
            "uploadURL": [
                74
            ],
            "__typename": [
                74
            ]
        },
        "ID": {},
        "Index": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "categoriesSection": [
                42
            ],
            "greeting": [
                74
            ],
            "popularArticlesSection": [
                65
            ],
            "rights": [
                74
            ],
            "socialMediaLinks": [
                70,
                {
                    "filter": [
                        72
                    ],
                    "first": [
                        54
                    ],
                    "orderBy": [
                        73
                    ],
                    "skip": [
                        54
                    ]
                }
            ],
            "subtitle": [
                77
            ],
            "__typename": [
                74
            ]
        },
        "InlineIconComponent": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "name": [
                74
            ],
            "tooltip": [
                74
            ],
            "__typename": [
                74
            ]
        },
        "Int": {},
        "JSON": {},
        "ListFilter": {
            "isEmpty": [
                36
            ],
            "length": [
                54
            ],
            "__typename": [
                74
            ]
        },
        "ListMeta": {
            "totalCount": [
                54
            ],
            "__typename": [
                74
            ]
        },
        "MetadataComponent": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "description": [
                74
            ],
            "icon": [
                29
            ],
            "ogImage": [
                31
            ],
            "title": [
                74
            ],
            "__typename": [
                74
            ]
        },
        "Mutation": {
            "getUploadSignedURL": [
                50,
                {
                    "fileHash": [
                        74
                    ],
                    "fileName": [
                        74,
                        "String!"
                    ]
                }
            ],
            "transaction": [
                74,
                {
                    "autoCommit": [
                        74
                    ],
                    "data": [
                        74,
                        "String!"
                    ],
                    "skipWorkflows": [
                        36
                    ]
                }
            ],
            "transactionAwaitable": [
                80,
                {
                    "autoCommit": [
                        74
                    ],
                    "data": [
                        74,
                        "String!"
                    ],
                    "skipWorkflows": [
                        36
                    ],
                    "timeout": [
                        54
                    ]
                }
            ],
            "transactionStatus": [
                80,
                {
                    "id": [
                        74,
                        "String!"
                    ]
                }
            ],
            "__typename": [
                74
            ]
        },
        "NavLinks": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_meta": [
                57
            ],
            "_searchKey": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "item": [
                61
            ],
            "items": [
                61
            ],
            "__typename": [
                74
            ]
        },
        "NavLinksItem": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "href": [
                74
            ],
            "__typename": [
                74
            ]
        },
        "NavLinksItemFilterInput": {
            "AND": [
                62
            ],
            "OR": [
                62
            ],
            "_sys_apiNamePath": [
                75
            ],
            "_sys_createdAt": [
                47
            ],
            "_sys_hash": [
                75
            ],
            "_sys_id": [
                75
            ],
            "_sys_idPath": [
                75
            ],
            "_sys_lastModifiedAt": [
                47
            ],
            "_sys_slug": [
                75
            ],
            "_sys_slugPath": [
                75
            ],
            "_sys_title": [
                75
            ],
            "href": [
                75
            ],
            "__typename": [
                74
            ]
        },
        "NavLinksItemOrderByEnum": {},
        "NumberFilter": {
            "eq": [
                49
            ],
            "gt": [
                49
            ],
            "gte": [
                49
            ],
            "lt": [
                49
            ],
            "lte": [
                49
            ],
            "neq": [
                49
            ],
            "__typename": [
                74
            ]
        },
        "PopularArticlesSection": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "articles": [
                2
            ],
            "title": [
                74
            ],
            "__typename": [
                74
            ]
        },
        "Query": {
            "_componentInstances": [
                84
            ],
            "_sys": [
                67
            ],
            "authors": [
                7,
                {
                    "filter": [
                        9
                    ],
                    "first": [
                        54
                    ],
                    "orderBy": [
                        10
                    ],
                    "skip": [
                        54
                    ]
                }
            ],
            "components": [
                44
            ],
            "index": [
                52
            ],
            "settings": [
                69
            ],
            "__typename": [
                74
            ]
        },
        "RepoSys": {
            "hash": [
                74
            ],
            "id": [
                51
            ],
            "slug": [
                74
            ],
            "title": [
                74
            ],
            "__typename": [
                74
            ]
        },
        "RichTextJson": {
            "content": [
                12
            ],
            "toc": [
                13
            ],
            "on_BaseRichTextJson": [
                22
            ],
            "on_BodyRichText": [
                35
            ],
            "on_ContentRichText": [
                46
            ],
            "on_SubtitleRichText": [
                78
            ],
            "__typename": [
                74
            ]
        },
        "Settings": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "intercomAppId": [
                74
            ],
            "logo": [
                29
            ],
            "logoLightMode": [
                29
            ],
            "metadata": [
                58
            ],
            "navLinks": [
                60,
                {
                    "filter": [
                        62
                    ],
                    "first": [
                        54
                    ],
                    "orderBy": [
                        63
                    ],
                    "skip": [
                        54
                    ]
                }
            ],
            "showUseTemplate": [
                36
            ],
            "theme": [
                79
            ],
            "__typename": [
                74
            ]
        },
        "SocialMediaLinks": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_meta": [
                57
            ],
            "_searchKey": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "item": [
                71
            ],
            "items": [
                71
            ],
            "__typename": [
                74
            ]
        },
        "SocialMediaLinksItem": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "platform": [
                19
            ],
            "url": [
                74
            ],
            "__typename": [
                74
            ]
        },
        "SocialMediaLinksItemFilterInput": {
            "AND": [
                72
            ],
            "OR": [
                72
            ],
            "_sys_apiNamePath": [
                75
            ],
            "_sys_createdAt": [
                47
            ],
            "_sys_hash": [
                75
            ],
            "_sys_id": [
                75
            ],
            "_sys_idPath": [
                75
            ],
            "_sys_lastModifiedAt": [
                47
            ],
            "_sys_slug": [
                75
            ],
            "_sys_slugPath": [
                75
            ],
            "_sys_title": [
                75
            ],
            "url": [
                75
            ],
            "__typename": [
                74
            ]
        },
        "SocialMediaLinksItemOrderByEnum": {},
        "String": {},
        "StringFilter": {
            "contains": [
                74
            ],
            "endsWith": [
                74
            ],
            "eq": [
                74
            ],
            "matches": [
                76
            ],
            "notEq": [
                74
            ],
            "startsWith": [
                74
            ],
            "__typename": [
                74
            ]
        },
        "StringMatchesFilter": {
            "caseSensitive": [
                36
            ],
            "pattern": [
                74
            ],
            "__typename": [
                74
            ]
        },
        "Subtitle": {
            "html": [
                74,
                {
                    "slugs": [
                        36
                    ],
                    "toc": [
                        36
                    ]
                }
            ],
            "json": [
                78
            ],
            "markdown": [
                74
            ],
            "plainText": [
                74
            ],
            "readingTime": [
                54,
                {
                    "wpm": [
                        54
                    ]
                }
            ],
            "__typename": [
                74
            ]
        },
        "SubtitleRichText": {
            "content": [
                12
            ],
            "toc": [
                13
            ],
            "__typename": [
                74
            ]
        },
        "Theme": {
            "_analyticsKey": [
                74,
                {
                    "scope": [
                        0
                    ]
                }
            ],
            "_id": [
                74
            ],
            "_idPath": [
                74
            ],
            "_slug": [
                74
            ],
            "_slugPath": [
                74
            ],
            "_sys": [
                27
            ],
            "_title": [
                74
            ],
            "accentColor": [
                16
            ],
            "appearance": [
                15
            ],
            "grayScale": [
                18
            ],
            "panelBackground": [
                21
            ],
            "radius": [
                14
            ],
            "scaling": [
                20
            ],
            "__typename": [
                74
            ]
        },
        "TransactionStatus": {
            "duration": [
                54
            ],
            "endedAt": [
                74
            ],
            "id": [
                74
            ],
            "message": [
                74
            ],
            "startedAt": [
                74
            ],
            "status": [
                81
            ],
            "__typename": [
                74
            ]
        },
        "TransactionStatusEnum": {},
        "UnionCalloutComponentInlineIconComponent": {
            "on_CalloutComponent": [
                37
            ],
            "on_InlineIconComponent": [
                53
            ],
            "on_BlockDocument": [
                26
            ],
            "__typename": [
                74
            ]
        },
        "Variant": {
            "apiName": [
                74
            ],
            "color": [
                74
            ],
            "id": [
                74
            ],
            "isDefault": [
                36
            ],
            "label": [
                74
            ],
            "__typename": [
                74
            ]
        },
        "_components": {
            "articlesItem": [
                1,
                {
                    "filter": [
                        3
                    ],
                    "first": [
                        54
                    ],
                    "orderBy": [
                        6
                    ],
                    "skip": [
                        54
                    ]
                }
            ],
            "authorsItem": [
                7,
                {
                    "filter": [
                        9
                    ],
                    "first": [
                        54
                    ],
                    "orderBy": [
                        10
                    ],
                    "skip": [
                        54
                    ]
                }
            ],
            "categoriesItem": [
                38,
                {
                    "filter": [
                        40
                    ],
                    "first": [
                        54
                    ],
                    "orderBy": [
                        41
                    ],
                    "skip": [
                        54
                    ]
                }
            ],
            "navLinksItem": [
                60,
                {
                    "filter": [
                        62
                    ],
                    "first": [
                        54
                    ],
                    "orderBy": [
                        63
                    ],
                    "skip": [
                        54
                    ]
                }
            ],
            "socialMediaLinksItem": [
                70,
                {
                    "filter": [
                        72
                    ],
                    "first": [
                        54
                    ],
                    "orderBy": [
                        73
                    ],
                    "skip": [
                        54
                    ]
                }
            ],
            "__typename": [
                74
            ]
        }
    }
}