apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chproxy.fullname" . }}
  labels:
    {{- include "chproxy.labels" . | nindent 4 }}
type: Opaque
data:
  clickhouse-url: {{ required "A valid .Values.env.CLICKHOUSE_URL is required" .Values.env.CLICKHOUSE_URL | b64enc }}
  basic-auth: {{ required "A valid .Values.env.BASIC_AUTH is required" .Values.env.BASIC_AUTH | b64enc }} 