name: Artifact Release
on:
    push:
        branches:
            - main
            - staging
    workflow_dispatch:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
            namespace:
                required: false
                type: string
                default: 'flowise'
            release_name:
                required: false
                type: string
                default: 'flowise'
            deployment_name:
                required: false
                type: string
                default: 'flowise'
        secrets:
            CLUSTER_ID:
                required: true
            DIGITALOCEAN_TOKEN:
                required: true
            POSTGRES_HOST:
                required: true
            POSTGRES_PORT:
                required: true
            POSTGRES_USER:
                required: true
            POSTGRES_PASSWORD:
                required: true
            POSTGRES_DATABASE:
                required: true

permissions:
    contents: write
    id-token: write
    packages: write

jobs:
    run:
        strategy:
            matrix:
                platform: [ubuntu-latest]
                node-version: [18.15.0]
        runs-on: ${{ matrix.platform }}
        env:
            PUPPETEER_SKIP_DOWNLOAD: true
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 9.0.4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  check-latest: false
                  cache: 'pnpm'
            - run: npm i -g pnpm
            - run: pnpm install
            - run: ./node_modules/.bin/cypress install
            - run: pnpm build
            - name: Install dependencies
              uses: cypress-io/github-action@v6
              with:
                  working-directory: ./
                  runTests: false
            - name: Cypress test
              uses: cypress-io/github-action@v6
              with:
                  install: false
                  working-directory: packages/server
                  start: pnpm start
                  wait-on: 'http://localhost:3000'
                  wait-on-timeout: 120
                  browser: chrome
    build-flowise:
        needs: run
        name: Build Flowise images for ${{ inputs.environment }}
        uses: ./.github/workflows/reusable-deploy-docker-artifacts.yml
        with:
            dockerfile: ./Dockerfile
            image-name: feelguuds/vector-workflow-manager
            context: .
            platform: linux/amd64
        secrets:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    deploy-flowise:
        if: github.event_name != 'pull_request'
        name: Deploy Flowise Service To DigitalOcean Kubernetes cluster ${{ inputs.environment }}
        uses: ./.github/workflows/reusable-k8s-deployment.yml
        needs:
            - build-flowise
        with:
            environment: ${{ github.ref == 'refs/heads/staging' && 'staging' || 'production' }}
            namespace: vector
            release_name: vector-workflow-manager
            app_root: .
            chart_name: vector-workflow-manager
            helm_timeout: '5m'
            kubeconfig_expiry: '600'
        secrets:
            DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
            CLUSTER_ID: ${{ secrets.CLUSTER_ID }}
            POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
            POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
            POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
